# --- COMA specific parameters ---

action_selector: "rlsac_soft_policies"
mask_before_softmax: False
save_model: True
save_model_interval: 20000

runner: "episode"

buffer_size: 10
batch_size_run: 1
batch_size: 1

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False


# use COMA
mac: "non_shared_mac"
agent: "sac_ns"
standardise_returns: False
standardise_rewards: True
use_rnn: False
agent_output_type: "pi_logits"
learner: "rlsac_coma_learner"
# critic_q_fn: "coma"
# critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
entropy_coef: 0.01
q_nstep: 5  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
critic_type: rlsac_coma_critic_ns

name: "rlsac_coma_ns"
t_max: 200500
# t_max: 20050000

data_dir: "/cluster/project/infk/courses/252-0579-00L/group19_2023/RANSAC-Tutorial-Data/"
# checkpoint_path: "/cluster/home/zhiyhuang/epymarl/results/models/rlsac_coma_ns_seed842894812_SACEnv-v1_2023-05-15 21:00:17.516200"
# evaluate: True
# render: True
use_tensorboard: True # Log results to tensorboard
